DEFAULT_PLAN_DATA = [
    {
        "category": "Website Development",
        "name": "Starter Website Plan",
        "price_one_time": "₹18,900",
        "price_monthly": "₹2,500/month",
        "best_for": "Early-stage startups and local businesses launching online.",
        "features": "Up to 5 pages\nResponsive UI\nBasic SEO setup\nLead form integration\n30-day support",
        "is_recommended": False,
    },
    {
        "category": "Website Development",
        "name": "Growth Website Plan",
        "price_one_time": "₹38,900",
        "price_monthly": "₹5,500/month",
        "best_for": "Brands targeting predictable lead generation and growth.",
        "features": "Up to 12 pages\nConversion-focused UX\nAdvanced SEO foundation\nBlog setup\nAnalytics dashboard",
        "is_recommended": True,
    },
    {
        "category": "Website Development",
        "name": "Pro Business Website",
        "price_one_time": "₹74,900",
        "price_monthly": "₹11,000/month",
        "best_for": "Established companies needing enterprise-level positioning.",
        "features": "Custom architecture\nPerformance tuning\nTechnical SEO + schema\nAutomation integrations\nPriority support",
        "is_recommended": False,
    },
    {
        "category": "E-Commerce Development",
        "name": "Basic",
        "price_one_time": "₹45,000",
        "price_monthly": "₹4,500/month",
        "best_for": "Single-brand stores launching first online catalog.",
        "features": "Catalog setup\nPayment gateway placeholder\nOrder management basics\nMobile optimized UI\nAdmin panel setup",
        "is_recommended": False,
    },
    {
        "category": "E-Commerce Development",
        "name": "Advanced",
        "price_one_time": "₹85,000",
        "price_monthly": "₹8,500/month",
        "best_for": "Growing D2C brands with regular campaign activity.",
        "features": "Advanced catalog system\nCoupon workflows\nCustomer analytics\nInventory notifications\nRetention automation hooks",
        "is_recommended": True,
    },
    {
        "category": "E-Commerce Development",
        "name": "Premium Smart",
        "price_one_time": "₹1,75,000+",
        "price_monthly": "₹15,000/month",
        "best_for": "High-volume stores and enterprise commerce systems.",
        "features": "Custom checkout flow\nWarehouse integrations\nSmart recommendation engine\nScalable infra architecture\nDedicated support",
        "is_recommended": False,
    },
    {
        "category": "Python Automation",
        "name": "Basic Script",
        "price_one_time": "₹7,500",
        "price_monthly": None,
        "best_for": "One repetitive task automated quickly.",
        "features": "Single workflow\nInput/output mapping\nBasic logging\nDocumentation",
        "is_recommended": False,
    },
    {
        "category": "Python Automation",
        "name": "Business Automation",
        "price_one_time": "₹28,000",
        "price_monthly": None,
        "best_for": "Teams automating daily operations across tools.",
        "features": "Multi-step workflow\nAPI integrations\nRetry logic\nMonitoring setup",
        "is_recommended": True,
    },
    {
        "category": "Python Automation",
        "name": "Advanced Smart",
        "price_one_time": "₹65,000+",
        "price_monthly": None,
        "best_for": "Complex process automation with decision intelligence.",
        "features": "Data pipeline automation\nQueue processing\nScalable architecture\nObservability",
        "is_recommended": False,
    },
    {
        "category": "AI Chatbot",
        "name": "FAQ",
        "price_one_time": "₹15,000",
        "price_monthly": None,
        "best_for": "Businesses needing 24/7 FAQ response automation.",
        "features": "FAQ ingestion\nWebsite embed\nBasic intent handling\nUsage summary",
        "is_recommended": False,
    },
    {
        "category": "AI Chatbot",
        "name": "Smart GPT",
        "price_one_time": "₹38,000",
        "price_monthly": None,
        "best_for": "Service businesses that need qualified lead conversations.",
        "features": "LLM prompting layer\nLead qualification flow\nContext memory\nEscalation to human",
        "is_recommended": True,
    },
    {
        "category": "AI Chatbot",
        "name": "CRM AI Assistant",
        "price_one_time": "₹95,000+",
        "price_monthly": None,
        "best_for": "Sales teams requiring CRM-integrated automation assistant.",
        "features": "CRM integration\nPipeline updates\nFollow-up automation\nConversation analytics",
        "is_recommended": False,
    },
    {
        "category": "SEO Services",
        "name": "Basic",
        "price_one_time": "₹9,000 one-time",
        "price_monthly": None,
        "best_for": "Foundational SEO setup for new websites.",
        "features": "Technical audit\nMeta optimization\nBasic keyword mapping\nIndexing setup",
        "is_recommended": False,
    },
    {
        "category": "SEO Services",
        "name": "Growth",
        "price_one_time": None,
        "price_monthly": "₹18,000/month",
        "best_for": "Brands seeking steady organic growth.",
        "features": "Content strategy\nOn-page optimization\nMonthly reporting\nCompetitor tracking",
        "is_recommended": True,
    },
    {
        "category": "SEO Services",
        "name": "Advanced",
        "price_one_time": None,
        "price_monthly": "₹35,000/month",
        "best_for": "Competitive industries with aggressive SEO goals.",
        "features": "Enterprise SEO roadmap\nTopical authority planning\nTechnical deep fixes\nCRO + SEO sync",
        "is_recommended": False,
    },
]


PLAN_DROPDOWN_OPTIONS = [
    "Starter Website Plan",
    "Growth Website Plan",
    "Pro Business Website",
    "E-Commerce Basic",
    "E-Commerce Advanced",
    "E-Commerce Premium Smart",
    "Python Automation Basic Script",
    "Python Automation Business Automation",
    "Python Automation Advanced Smart",
    "AI Chatbot FAQ",
    "AI Chatbot Smart GPT",
    "AI Chatbot CRM AI Assistant",
    "SEO Basic",
    "SEO Growth",
    "SEO Advanced",
]
