DEFAULT_PLAN_DATA = [
    {
        "category": "Website Development",
        "name": "Starter Website Plan",
        "price_one_time": "₹18,900",
        "price_monthly": "₹2,500/month",
        "best_for": "Early-stage startups and local businesses launching online.",
        "features": "Up to 5 pages\nResponsive UI\nBasic SEO setup\nLead form integration\n30-day support",
        "is_recommended": False,
    },
    {
        "category": "Website Development",
        "name": "Growth Website Plan",
        "price_one_time": "₹38,900",
        "price_monthly": "₹5,500/month",
        "best_for": "Brands targeting predictable lead generation and growth.",
        "features": "Up to 12 pages\nConversion-focused UX\nAdvanced SEO foundation\nBlog setup\nAnalytics dashboard",
        "is_recommended": True,
    },
    {
        "category": "Website Development",
        "name": "Pro Business Website",
        "price_one_time": "₹74,900",
        "price_monthly": "₹11,000/month",
        "best_for": "Established companies needing enterprise-level positioning.",
        "features": "Custom architecture\nPerformance tuning\nTechnical SEO + schema\nAutomation integrations\nPriority support",
        "is_recommended": False,
    },
    {
        "category": "E-Commerce Development",
        "name": "Basic",
        "price_one_time": "₹45,000",
        "price_monthly": "₹4,500/month",
        "best_for": "Single-brand stores launching first online catalog.",
        "features": "Catalog setup\nPayment gateway placeholder\nOrder management basics\nMobile optimized UI\nAdmin panel setup",
        "is_recommended": False,
    },
    {
        "category": "E-Commerce Development",
        "name": "Advanced",
        "price_one_time": "₹85,000",
        "price_monthly": "₹8,500/month",
        "best_for": "Growing D2C brands with regular campaign activity.",
        "features": "Advanced catalog system\nCoupon workflows\nCustomer analytics\nInventory notifications\nRetention automation hooks",
        "is_recommended": True,
    },
    {
        "category": "E-Commerce Development",
        "name": "Premium Smart",
        "price_one_time": "₹1,75,000+",
        "price_monthly": "₹15,000/month",
        "best_for": "High-volume stores and enterprise commerce systems.",
        "features": "Custom checkout flow\nWarehouse integrations\nSmart recommendation engine\nScalable infra architecture\nDedicated support",
        "is_recommended": False,
    },
    {
        "category": "Python Automation",
        "name": "Basic Script",
        "price_one_time": "₹7,500",
        "price_monthly": "₹1,500/month",
        "best_for": "One repetitive task automated quickly.",
        "features": "Single workflow\nInput/output mapping\nBasic logging\nDocumentation",
        "is_recommended": False,
    },
    {
        "category": "Python Automation",
        "name": "Business Automation",
        "price_one_time": "₹28,000",
        "price_monthly": "₹4,000/month",
        "best_for": "Teams automating daily operations across tools.",
        "features": "Multi-step workflow\nAPI integrations\nRetry logic\nMonitoring setup",
        "is_recommended": True,
    },
    {
        "category": "Python Automation",
        "name": "Advanced Smart",
        "price_one_time": "₹65,000+",
        "price_monthly": "₹9,000/month",
        "best_for": "Complex process automation with decision intelligence.",
        "features": "Data pipeline automation\nQueue processing\nScalable architecture\nObservability",
        "is_recommended": False,
    },
    {
        "category": "AI Chatbot",
        "name": "FAQ",
        "price_one_time": "₹15,000",
        "price_monthly": "₹2,000/month",
        "best_for": "Businesses needing 24/7 FAQ response automation.",
        "features": "FAQ ingestion\nWebsite embed\nBasic intent handling\nUsage summary",
        "is_recommended": False,
    },
    {
        "category": "AI Chatbot",
        "name": "Smart GPT",
        "price_one_time": "₹38,000",
        "price_monthly": "₹5,000/month",
        "best_for": "Service businesses that need qualified lead conversations.",
        "features": "LLM prompting layer\nLead qualification flow\nContext memory\nEscalation to human",
        "is_recommended": True,
    },
    {
        "category": "AI Chatbot",
        "name": "CRM AI Assistant",
        "price_one_time": "₹95,000+",
        "price_monthly": "₹12,000/month",
        "best_for": "Sales teams requiring CRM-integrated automation assistant.",
        "features": "CRM integration\nPipeline updates\nFollow-up automation\nConversation analytics",
        "is_recommended": False,
    },
    {
        "category": "SEO Services",
        "name": "Basic",
        "price_one_time": "₹9,000 one-time",
        "price_monthly": "₹4,000/month",
        "best_for": "Foundational SEO setup for new websites.",
        "features": "Technical audit\nMeta optimization\nBasic keyword mapping\nIndexing setup",
        "is_recommended": False,
    },
    {
        "category": "SEO Services",
        "name": "Growth",
        "price_one_time": None,
        "price_monthly": "₹18,000/month",
        "best_for": "Brands seeking steady organic growth.",
        "features": "Content strategy\nOn-page optimization\nMonthly reporting\nCompetitor tracking",
        "is_recommended": True,
    },
    {
        "category": "SEO Services",
        "name": "Advanced",
        "price_one_time": None,
        "price_monthly": "₹35,000/month",
        "best_for": "Competitive industries with aggressive SEO goals.",
        "features": "Enterprise SEO roadmap\nTopical authority planning\nTechnical deep fixes\nCRO + SEO sync",
        "is_recommended": False,
    },
]


MAINTENANCE_PLAN_DATA = {
    "Website Development": {
        "Starter Website Plan": {
            "price_monthly": "₹2,500/month",
            "best_for": "Businesses needing stable monthly support for a lightweight website.",
            "features": [
                "Hosting & deployment support",
                "Security patch updates",
                "Bug fixing & error resolution",
                "Monthly website backup",
                "Minor content updates (up to 2 changes/month)",
                "Basic uptime monitoring",
            ],
        },
        "Growth Website Plan": {
            "price_monthly": "₹5,500/month",
            "best_for": "Growing brands that need performance and SEO-focused maintenance.",
            "features": [
                "Everything in Starter Plan",
                "Performance monitoring & speed optimization",
                "SEO monitoring (on-page tracking)",
                "Database backup management",
                "Content updates (up to 5 changes/month)",
                "Broken link checks",
                "Priority email support",
            ],
        },
        "Pro Business Website": {
            "price_monthly": "₹11,000/month",
            "best_for": "Established businesses requiring proactive technical oversight.",
            "features": [
                "Everything in Growth Plan",
                "Server health monitoring",
                "Security hardening updates",
                "Small feature enhancements",
                "Automation monitoring (if integrated)",
                "Monthly performance report",
                "Emergency technical support",
                "Advanced backup management (weekly)",
            ],
        },
    },
    "E-Commerce Development": {
        "Basic": {
            "price_monthly": "₹4,500/month",
            "best_for": "Stores needing dependable monthly operations support.",
            "features": [
                "Payment gateway monitoring",
                "Security updates",
                "Order system monitoring",
                "Product upload support (20 products/month)",
                "Backup management",
                "Bug fixes",
            ],
        },
        "Advanced": {
            "price_monthly": "₹8,500/month",
            "best_for": "Growing stores running frequent campaigns and catalog updates.",
            "features": [
                "Everything in Basic Plan",
                "Sales performance tracking",
                "Automation monitoring",
                "Product upload support (50 products/month)",
                "Speed & performance optimization",
                "Coupon/discount monitoring",
                "Database optimization",
            ],
        },
        "Premium Smart": {
            "price_monthly": "₹15,000/month",
            "best_for": "High-scale commerce systems with automation and analytics dependencies.",
            "features": [
                "Full automation supervision",
                "CRM sync monitoring",
                "AI chatbot monitoring",
                "Payment system diagnostics",
                "Monthly analytics & sales report",
                "Minor feature upgrades",
                "Server performance optimization",
                "Priority technical support",
            ],
        },
    },
    "Python Automation": {
        "Basic Script": {
            "price_monthly": "₹1,500/month",
            "best_for": "Small automations that need occasional fixes and upkeep.",
            "features": [
                "Bug fixing",
                "Minor logic updates",
                "Compatibility updates",
                "Error troubleshooting",
            ],
        },
        "Business Automation": {
            "price_monthly": "₹4,000/month",
            "best_for": "Operational workflows requiring regular monitoring and tuning.",
            "features": [
                "Automation workflow monitoring",
                "Log tracking & debugging",
                "Performance tuning",
                "Minor logic improvements",
                "Data integrity checks",
                "Monthly health check",
            ],
        },
        "Advanced Smart": {
            "price_monthly": "₹9,000/month",
            "best_for": "Critical multi-system automations needing deep oversight.",
            "features": [
                "Full system monitoring",
                "API health checks",
                "Error handling improvements",
                "Workflow scaling adjustments",
                "Monthly system audit report",
                "Optimization for performance & efficiency",
                "Emergency issue resolution",
            ],
        },
    },
    "AI Chatbot": {
        "FAQ": {
            "price_monthly": "₹2,000/month",
            "best_for": "Basic FAQ bots that need routine refreshes.",
            "features": [
                "FAQ updates",
                "Minor retraining",
                "Bug fixes",
                "Chat flow improvements",
            ],
        },
        "Smart GPT": {
            "price_monthly": "₹5,000/month",
            "best_for": "Lead-focused GPT bots requiring quality and response tuning.",
            "features": [
                "Prompt tuning & optimization",
                "Response quality monitoring",
                "Database syncing checks",
                "Lead capture testing",
                "Performance tracking",
            ],
        },
        "CRM AI Assistant": {
            "price_monthly": "₹12,000/month",
            "best_for": "CRM-integrated assistants with continuous optimization needs.",
            "features": [
                "AI retraining & improvement",
                "CRM integration monitoring",
                "Automation optimization",
                "Lead qualification monitoring",
                "Monthly analytics report",
                "Performance & accuracy tuning",
                "System stability monitoring",
            ],
        },
    },
    "SEO Services": {
        "Basic": {
            "price_monthly": "₹4,000/month",
            "best_for": "Foundational monthly SEO continuity for small websites.",
            "features": [
                "Keyword tracking",
                "On-page optimization updates",
                "2 blog optimizations",
                "Basic ranking report",
            ],
        },
        "Growth": {
            "price_monthly": "₹18,000/month",
            "best_for": "Brands aiming for sustained organic growth with active optimization.",
            "features": [
                "Technical SEO monitoring",
                "4 blog optimizations",
                "Backlink outreach",
                "Performance analysis",
                "Competitor monitoring",
            ],
        },
        "Advanced": {
            "price_monthly": "₹35,000/month",
            "best_for": "Competitive markets requiring deep SEO and conversion alignment.",
            "features": [
                "Full technical SEO audits",
                "Content strategy updates",
                "Conversion optimization",
                "Competitor deep analysis",
                "Advanced keyword research",
                "Monthly growth report",
            ],
        },
    },
}


PLAN_DROPDOWN_OPTIONS = [
    "Starter Website Plan",
    "Growth Website Plan",
    "Pro Business Website",
    "E-Commerce Basic",
    "E-Commerce Advanced",
    "E-Commerce Premium Smart",
    "Python Automation Basic Script",
    "Python Automation Business Automation",
    "Python Automation Advanced Smart",
    "AI Chatbot FAQ",
    "AI Chatbot Smart GPT",
    "AI Chatbot CRM AI Assistant",
    "SEO Basic",
    "SEO Growth",
    "SEO Advanced",
]
