"""baseline schema

Revision ID: 33f47b0d9d6d
Revises: 
Create Date: 2026-03-03 19:55:21.109989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f47b0d9d6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_email', sa.String(length=180), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)

    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)

    op.create_table('automation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_logs_service_name'), ['service_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_logs_status'), ['status'], unique=False)

    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_session_id'), ['session_id'], unique=False)

    op.create_table('contact_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('company', sa.String(length=180), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('selected_plan', sa.String(length=120), nullable=True),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_leads_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_leads_status'), ['status'], unique=False)

    op.create_table('notification_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=120), nullable=False),
    sa.Column('client_email', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=120), nullable=False),
    sa.Column('client_email', sa.String(length=180), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('payment_gateway', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('plan_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price_one_time', sa.String(length=60), nullable=True),
    sa.Column('price_monthly', sa.String(length=60), nullable=True),
    sa.Column('best_for', sa.String(length=180), nullable=False),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_catalog_category'), ['category'], unique=False)

    op.create_table('plan_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('service_type', sa.String(length=120), nullable=False),
    sa.Column('plan_name', sa.String(length=120), nullable=False),
    sa.Column('project_details', sa.Text(), nullable=False),
    sa.Column('timeline', sa.String(length=80), nullable=True),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_inquiries_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_inquiries_service_type'), ['service_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_inquiries_status'), ['status'], unique=False)

    op.create_table('portfolio_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tech_stack', sa.String(length=255), nullable=False),
    sa.Column('project_url', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_projects_slug'), ['slug'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=180), nullable=True),
    sa.Column('testimonial', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('client_image', sa.String(length=255), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('excerpt', sa.String(length=280), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_posts_slug'), ['slug'], unique=True)

    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('cart_items')
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_slug'))

    op.drop_table('blog_posts')
    op.drop_table('testimonials')
    op.drop_table('products')
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_projects_slug'))

    op.drop_table('portfolio_projects')
    with op.batch_alter_table('plan_inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_inquiries_status'))
        batch_op.drop_index(batch_op.f('ix_plan_inquiries_service_type'))
        batch_op.drop_index(batch_op.f('ix_plan_inquiries_email'))

    op.drop_table('plan_inquiries')
    with op.batch_alter_table('plan_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_catalog_category'))

    op.drop_table('plan_catalog')
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_table('notification_alerts')
    with op.batch_alter_table('contact_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_leads_status'))
        batch_op.drop_index(batch_op.f('ix_contact_leads_email'))

    op.drop_table('contact_leads')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_session_id'))

    op.drop_table('cart')
    with op.batch_alter_table('automation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_logs_status'))
        batch_op.drop_index(batch_op.f('ix_automation_logs_service_name'))
        batch_op.drop_index(batch_op.f('ix_automation_logs_created_at'))

    op.drop_table('automation_logs')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
